# Generated by Django 4.0.6 on 2022-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_activation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uploaded_volume',
            field=models.IntegerField(default=0, verbose_name='user uploaded volume(byte)'),
        ),
    ]
