# Generated by Django 4.0.6 on 2022-08-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_uploaded_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uploaded_volume',
            field=models.IntegerField(blank=True, default=0, verbose_name='user uploaded volume(byte)'),
        ),
    ]
