# Generated by Django 4.0.6 on 2022-08-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemanager',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='size(bytes)'),
        ),
    ]
