# Generated by Django 4.0.6 on 2022-08-17 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0002_alter_filemanager_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemanager',
            options={'ordering': ['-created_time']},
        ),
    ]
